### ISSUE TITLE
Add second degree sorting parameter

### ISSUE THREAD

**Issue by mandavister** [panvicka/selector-front#56]
When sorting by Moderator, add second sorting parameter „last time“ to show lazy people first who have the same Moderator-count

**Comment by panvicka** [comment]
It is not possible to pre-sort the table with the used Grid.js library. I added a button for each role that will sort the table based on the two role relevant columns. Check it here https://jam.dev/c/e564c62f-e522-4574-8152-8aae6fff7d68 Would that be also acceptable for u? 

I want to get rid of the Grid.Js tables anyway so this is probably temporary solution (those last the longest 😆 )

Also testable on branch https://deploy-preview-57--dev-seelector.netlify.app/ (dm me for basic auth)
