### ISSUE TITLE
Event doesn't show in People list

### ISSUE THREAD

**Issue by mandavister** [panvicka/selector-front#67]
Although the TS event of the 2023-07-14 is listed in the Event List https://selector.infra.bitgrip.berlin/items/636b4b8d01f350e3c2177972 it doesn't show in the People List of Johannes Russ - though it's present in the Recorder list of Roman.

Screenshot on request - can't upload here :(

**Comment by panvicka** [comment]
What you probably want is to have a look at Event List, not People List. 
<img width="1437" alt="image" src="https://github.com/panvicka/selector-front/assets/64703124/1a026527-58ee-482b-a59e-1c9640de6a0c">
